In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
# PREPARING THE DATA

In [4]:
npf_train = pd.read_csv("npf_train.csv")
npf_train = npf_train.drop("partlybad",axis=1)
npf_train

,id,date,class4,CO2168.mean,CO2168.std,CO2336.mean,CO2336.std,CO242.mean,CO242.std,CO2504.mean,...,T672.mean,T672.std,T84.mean,T84.std,UV_A.mean,UV_A.std,UV_B.mean,UV_B.std,CS.mean,CS.std
0,1,2000-01-01,nonevent,384.462000,2.284996,384.164462,2.135062,385.274688,2.211695,383.885077,...,-13.016471,0.525698,-12.422972,0.376324,1.635563,0.856948,0.026438,0.014617,0.003374,0.000733
1,2,2000-01-20,nonevent,374.884615,0.415185,374.703333,0.385179,375.621266,0.665720,374.674177,...,-8.997430,0.373927,-8.351043,0.575679,1.441109,0.741088,0.022649,0.012479,0.001501,0.000572
2,3,2000-01-23,nonevent,373.496585,0.189497,373.382593,0.172958,373.961481,0.235107,373.275062,...,-10.224472,0.965988,-9.651155,1.238891,2.677545,1.261612,0.044759,0.023748,0.000764,0.000048
3,4,2000-02-17,nonevent,378.600367,1.934180,378.464862,1.946536,379.785872,2.865022,378.316909,...,-1.535183,0.122651,-0.829524,0.134191,2.261805,1.345651,0.030893,0.021903,0.002038,0.000751
4,5,2000-03-25,Ib,373.128684,1.096617,372.980000,1.047750,373.701830,1.259198,372.910000,...,-2.095641,1.695622,-1.095864,2.090111,12.906779,7.022300,0.333523,0.239981,0.000662,0.000210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,454,2011-08-14,nonevent,377.541538,6.391551,377.802756,6.187754,380.131355,8.036365,377.507244,...,16.470062,2.142789,17.077060,2.779125,16.129744,12.203500,0.786032,0.696306,0.002360,0.000253
454,455,2011-08-16,nonevent,381.016623,4.411571,381.030844,4.062115,382.901742,5.061991,381.072078,...,16.319361,1.089563,17.268471,1.308728,8.688739,8.320799,0.464422,0.496816,0.002423,0.000425
455,456,2011-08-18,nonevent,386.687895,12.065627,386.284079,11.751004,392.981111,14.968791,386.336908,...,13.315270,0.511146,13.781909,0.838839,7.375727,5.115708,0.366155,0.316015,0.001993,0.000391
456,457,2011-08-21,nonevent,379.279128,12.045785,379.363087,11.533353,381.268591,14.043508,379.163200,...,14.421092,1.696894,15.094141,1.745526,8.099394,5.851942,0.416961,0.363890,0.003484,0.000457
457,458,2011-08-22,nonevent,384.443758,6.413297,384.364392,5.781036,386.384762,7.663215,384.186892,...,15.049728,0.969001,16.076217,1.197644,11.665070,10.062797,0.622831,0.595032,0.004782,0.001082

In [5]:
# COPYING MODIFICATIONS FROM e1t1

npf_train = npf_train.set_index("date")
## Tell that "class4" is categorical variable. (R does this automatically.)
npf_train["class4"] = npf_train["class4"].astype("category")

## Here date column was converted to index and we do not need to get rid of it.
npf_train = npf_train.drop("id",axis=1)

## If you don't use dtype="object" array will cut strings...
class2 = np.array(["event"]*npf_train.shape[0],dtype="object")
class2[npf_train["class4"]=="nonevent"] = "nonevent"
npf_train["class2"] = class2
npf_train["class2"] = npf_train["class2"].astype("category")

In [6]:
npf_train

,class4,CO2168.mean,CO2168.std,CO2336.mean,CO2336.std,CO242.mean,CO242.std,CO2504.mean,CO2504.std,Glob.mean,...,T672.std,T84.mean,T84.std,UV_A.mean,UV_A.std,UV_B.mean,UV_B.std,CS.mean,CS.std,class2
date,,,,,,,,,,,,,,,,,,,,,
2000-01-01,nonevent,384.462000,2.284996,384.164462,2.135062,385.274688,2.211695,383.885077,1.955198,19.245511,...,0.525698,-12.422972,0.376324,1.635563,0.856948,0.026438,0.014617,0.003374,0.000733,nonevent
2000-01-20,nonevent,374.884615,0.415185,374.703333,0.385179,375.621266,0.665720,374.674177,0.435480,31.107659,...,0.373927,-8.351043,0.575679,1.441109,0.741088,0.022649,0.012479,0.001501,0.000572,nonevent
2000-01-23,nonevent,373.496585,0.189497,373.382593,0.172958,373.961481,0.235107,373.275062,0.165500,29.800885,...,0.965988,-9.651155,1.238891,2.677545,1.261612,0.044759,0.023748,0.000764,0.000048,nonevent
2000-02-17,nonevent,378.600367,1.934180,378.464862,1.946536,379.785872,2.865022,378.316909,1.983430,23.795211,...,0.122651,-0.829524,0.134191,2.261805,1.345651,0.030893,0.021903,0.002038,0.000751,nonevent
2000-03-25,Ib,373.128684,1.096617,372.980000,1.047750,373.701830,1.259198,372.910000,1.004164,252.480327,...,1.695622,-1.095864,2.090111,12.906779,7.022300,0.333523,0.239981,0.000662,0.000210,event
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011-08-14,nonevent,377.541538,6.391551,377.802756,6.187754,380.131355,8.036365,377.507244,5.398886,270.743458,...,2.142789,17.077060,2.779125,16.129744,12.203500,0.786032,0.696306,0.002360,0.000253,nonevent
2011-08-16,nonevent,381.016623,4.411571,381.030844,4.062115,382.901742,5.061991,381.072078,3.840630,121.227780,...,1.089563,17.268471,1.308728,8.688739,8.320799,0.464422,0.496816,0.002423,0.000425,nonevent
2011-08-18,nonevent,386.687895,12.065627,386.284079,11.751004,392.981111,14.968791,386.336908,11.457833,108.311442,...,0.511146,13.781909,0.838839,7.375727,5.115708,0.366155,0.316015,0.001993,0.000391,nonevent
2011-08-21,nonevent,379.279128,12.045785,379.363087,11.533353,381.268591,14.043508,379.163200,10.932955,114.298822,...,1.696894,15.094141,1.745526,8.099394,5.851942,0.416961,0.363890,0.003484,0.000457,nonevent
2011-08-22,nonevent,384.443758,6.413297,384.364392,5.781036,386.384762,7.663215,384.186892,5.506259,180.454576,...,0.969001,16.076217,1.197644,11.665070,10.062797,0.622831,0.595032,0.004782,0.001082,nonevent

In [7]:
# BUILDING THE CLASSIFIERS

In [8]:
# I will just train a basic model fpr each model family,
# compare the results and choose the one with the best accuracy/lowest test error

In [9]:
# creating a df to store the models and results in
models = pd.DataFrame()
models["model"] = ["LDA", "QDA", "log regr", "nB", "KNN k=10", "KNN k = 20", "KNN k = 30", "decision tree", "random forest"]
models = models.set_index("model")
models

# seperating X and y from the training data # !!!!!!! we predict class 2 for now !!!!!!!


# reformating X to numerics
for i in range(1,101): # 101 because we have 102 columns
    npf_train.iloc[:,i] = pd.to_numeric(list(npf_train.iloc[:,i]))

## REDUCING the set to get a training and a test set (360 ~ 80% of 458)
X = npf_train.iloc[:360, 1:-1]
#y = [1 if i == "event" else 0 for i in npf_train.iloc[:360,-1]] # 1: event, 0: nonevent
y = npf_train.iloc[:360, -1]

# imports for the models
import sklearn
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# LDA
model_lda = LinearDiscriminantAnalysis()
t_model_lda = model_lda.fit(X, y)

# QDA
model_qda = QuadraticDiscriminantAnalysis()
t_model_qda = model_qda.fit(X, y)

# logistic regression
model_lr = LogisticRegression()
t_model_lr = model_lr.fit(X, y)

# naive Bayes
model_nb = GaussianNB()
t_model_nb = model_nb.fit(X, y)

# KNN
model_knn10 = KNeighborsClassifier(n_neighbors = 10)
t_model_knn10 = model_knn10.fit(X, y)
model_knn20 = KNeighborsClassifier(n_neighbors = 20)
t_model_knn20 = model_knn20.fit(X, y)
model_knn30 = KNeighborsClassifier(n_neighbors = 30)
t_model_knn30 = model_knn30.fit(X, y)

# decision tree
model_dt = DecisionTreeClassifier()
t_model_dt = model_dt.fit(X,y)

# random forest
model_rf = RandomForestClassifier()
t_model_rf = model_rf.fit(X,y)

# add trained models to df
models["trained_models"] = [t_model_lda, t_model_qda, t_model_lr, t_model_nb, t_model_knn10, t_model_knn20, t_model_knn30, t_model_dt, t_model_rf]
models

# show choice of category
# show probability of belonging to event
# show test error

/opt/conda/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

                                                  trained_models
model
LDA                                 LinearDiscriminantAnalysis()
QDA                              QuadraticDiscriminantAnalysis()
log regr                                    LogisticRegression()
nB                                                  GaussianNB()
KNN k=10                    KNeighborsClassifier(n_neighbors=10)
KNN k = 20                  KNeighborsClassifier(n_neighbors=20)
KNN k = 30                  KNeighborsClassifier(n_neighbors=30)
decision tree                           DecisionTreeClassifier()
random forest  (DecisionTreeClassifier(max_features='auto', r...

In [10]:
# our test set:
X_test = npf_train.iloc[360:, 1:-1]
y_test = npf_train.iloc[360:, -1]
# computing the scores
scores = []
for i in models.iloc[:, 0]:
    scores.append(i.score(X_test, y_test))
    
models["test score"] = scores
models


# --> logistic regression! (when random forest is not considered)

                                                  trained_models  test score
model
LDA                                 LinearDiscriminantAnalysis()    0.785714
QDA                              QuadraticDiscriminantAnalysis()    0.653061
log regr                                    LogisticRegression()    0.867347
nB                                                  GaussianNB()    0.785714
KNN k=10                    KNeighborsClassifier(n_neighbors=10)    0.795918
KNN k = 20                  KNeighborsClassifier(n_neighbors=20)    0.816327
KNN k = 30                  KNeighborsClassifier(n_neighbors=30)    0.806122
decision tree                           DecisionTreeClassifier()    0.836735
random forest  (DecisionTreeClassifier(max_features='auto', r...    0.908163

In [9]:
# improve results by: cross validation, dimensionality reduction, Lassoing ...